FROM ruby:3.3-slim

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential libpq-dev git curl libyaml-dev pkg-config \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Gems の配置先と実行ファイルにPATHを通す
ENV GEM_HOME=/usr/local/bundle
ENV BUNDLE_PATH=/usr/local/bundle
ENV PATH="$GEM_HOME/bin:$PATH"
